apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-oke
  labels:
    app: hello-oke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-oke
  template:
    metadata:
      labels:
        app: hello-oke
    spec:
      imagePullSecrets:
      - name: ocirsecret
      containers:
      - name: hello-oke
        image: ocir.sa-valparaiso-1.oci.oraclecloud.com/axdmxgyqpf22/repojoedayz/hello-oke:TAG
        ports:
        - containerPort: 80

